menu:
    Blog: /
    Archive: /archives
    CV: /CV
    About: /about
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: thirteenyu
duoshuo: 

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2010

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
